// Generates src/styles/tokens.css from design-system/tokens.json, the single source of truth.
import { readFileSync, writeFileSync } from 'node:fs';

const t = JSON.parse(readFileSync(new URL('../design-system/tokens.json', import.meta.url)));
const decl = (name, v) => `  --${name}: ${v};`;
const flat = ['spacing', 'radius', 'layout', 'duration', 'easing'].flatMap((g) => t[g].tokens.map((k) => decl(k.name, k.value)));
const fam = Object.entries(t.type.families).map(([k, v]) => decl(`font-${k}`, v));
const theme = (id) => t.color.tokens.map((k) => decl(k.name, k.value[id])).join('\n');

writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), `/* Generated by scripts/tokens.mjs from design-system/tokens.json. Do not edit. */
:root {
${[...fam, ...flat].join('\n')}
}
:root, [data-theme="dark"] {
  color-scheme: dark;
${theme('dark')}
}
[data-theme="light"] {
  color-scheme: light;
${theme('light')}
}
`);
